# Generated by Django 4.0.6 on 2022-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(null=True, verbose_name='Примечания'),
        ),
    ]
